[tool.poetry]
name = "workflow"
version = "0.1.0"
description = ""
authors = ["chibadaimare"]

[tool.poetry.dependencies]
python = "^3.7"
sklearn = "^0.0"
pandas = "*"
numpy = "*"
matplotlib = "*"
seaborn = "*"
japanize-matplotlib = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
scipy = "^1.5.1"
jupyterlab = "^3.6.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
